### ISSUE TITLE
Kotlin Incompatibility

### ISSUE THREAD

**Issue by Jooie** [techquest/isw-mobile-payment-sdk-android#3]
Configuring the sdk in kotlin throws an Unresolved Reference error when initializing using kotlin. Only works when done in java.

**Comment by ebi-igweze** [comment]
Hello @Jooie can you post the logs or stack trace of the error here.

**Comment by ebi-igweze** [comment]
hello, pls can you update the sdk version to at least 1.0.2, that version resolves this issue.
