### ISSUE TITLE
Gradle import issue

### ISSUE THREAD

**Issue by bailang1208** [techquest/isw-mobile-payment-sdk-android#6]
I can't import this library with gradle.
![Screenshot 2020-10-13 025145](https://user-images.githubusercontent.com/32005655/95780795-21e85480-0cff-11eb-8381-8a838baef601.png)

**Comment by ebi-igweze** [comment]
hello @bailang1208, update to the latest version and make sure you have the __techquest__ maven repository in your project __build.gradle__
